import Vue from 'vue'
import {
  Affix,
  Alert,
  Anchor,
  AnchorLink,
  AutoComplete,
  Avatar,
  BackTop,
  Badge,
  Breadcrumb,
  BreadcrumbItem,
  Button,
  ButtonGroup,
  Card,
  Carousel,
  CarouselItem,
  Cascader,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Col,
  Collapse,
  ColorPicker,
  Content,
  DatePicker,
  Divider,
  Drawer,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Footer,
  Form,
  FormItem,
  Header,
  Icon,
  Input,
  InputNumber,
  Scroll,
  Sider,
  Split,
  Submenu,
  Layout,
  List,
  // ListItem,
  // ListItemMeta,
  LoadingBar,
  Menu,
  MenuGroup,
  MenuItem,
  Message,
  Modal,
  Notice,
  Option,
  OptionGroup,
  Page,
  Panel,
  Poptip,
  Progress,
  Radio,
  RadioGroup,
  Rate,
  Row,
  Select,
  Slider,
  Spin,
  Step,
  Steps,
  Table,
  Tabs,
  TabPane,
  Tag,
  Time,
  Timeline,
  TimelineItem,
  TimePicker,
  Tooltip,
  Transfer,
  Tree,
  Upload,
  // ISwitch,
  Switch
} from 'view-design'

import 'view-design/dist/styles/iview.css'

const components = {
  Affix: Affix,
  Alert: Alert,
  Anchor: Anchor,
  AnchorLink: AnchorLink,
  AutoComplete: AutoComplete,
  Avatar: Avatar,
  BackTop: BackTop,
  Badge: Badge,
  Breadcrumb: Breadcrumb,
  BreadcrumbItem: BreadcrumbItem,
  Button: Button,
  ButtonGroup: ButtonGroup,
  Card: Card,
  Carousel: Carousel,
  CarouselItem: CarouselItem,
  Cascader: Cascader,
  Cell: Cell,
  CellGroup: CellGroup,
  Checkbox: Checkbox,
  CheckboxGroup: CheckboxGroup,
  Col: Col,
  Collapse: Collapse,
  ColorPicker: ColorPicker,
  Content: Content,
  DatePicker: DatePicker,
  Divider: Divider,
  Drawer: Drawer,
  Dropdown: Dropdown,
  DropdownItem: DropdownItem,
  DropdownMenu: DropdownMenu,
  Footer: Footer,
  Form: Form,
  FormItem: FormItem,
  Header: Header,
  Icon: Icon,
  Input: Input,
  InputNumber: InputNumber,
  Scroll: Scroll,
  Sider: Sider,
  Split: Split,
  Submenu: Submenu,
  Layout: Layout,
  List: List,
  ListItem: List.ListItem,
  ListItemMeta: List.ListItemMeta,
  LoadingBar: LoadingBar,
  Menu: Menu,
  MenuGroup: MenuGroup,
  MenuItem: MenuItem,
  Message: Message,
  Modal: Modal,
  Notice: Notice,
  Option: Option,
  OptionGroup: OptionGroup,
  Page: Page,
  Panel: Panel,
  Poptip: Poptip,
  Progress: Progress,
  Radio: Radio,
  RadioGroup: RadioGroup,
  Rate: Rate,
  Row: Row,
  Select: Select,
  Slider: Slider,
  Spin: Spin,
  Step: Step,
  Steps: Steps,
  Table: Table,
  Tabs: Tabs,
  TabPane: TabPane,
  Tag: Tag,
  Time: Time,
  Timeline: Timeline,
  TimelineItem: TimelineItem,
  TimePicker: TimePicker,
  Tooltip: Tooltip,
  Transfer: Transfer,
  Tree: Tree,
  Upload: Upload
}
const icomponents = {
  ...components,
  'i-col': Col,
  'i-switch': Switch
}

Object.keys(icomponents).forEach(key => {
  Vue.component(key, icomponents[key])
})

Vue.prototype.$Loading = LoadingBar
Vue.prototype.$Message = Message
Vue.prototype.$Modal = Modal
Vue.prototype.$Notice = Notice
Vue.prototype.$Spin = Spin

export default {
  LoadingBar,
  Message,
  Modal,
  Notice,
  Spin
}
